### ISSUE TITLE
Questions regarding the use of HMACs in password security

### ISSUE THREAD

**Issue by bojtalepenye** [JakeWnuk/ptt#46]
## Initial thoughts
I have read a bit into the amazing slides you have released about password cracking, and I wanted to ask a few questions related to HMACs (Hash-based message authentication codes). In the "Defending Applications" section you mentioned that for example HMAC-Bcrypt is used for legacy systems and systems that cannot tolerate any authentication latency.

## HMAC - How they work... (as of my understanding)
First and foremost these are the core parts that make a HMAC a HMAC:
- Ensures that a message has not been altered (integrity) and verifies that it comes from a trusted source (authenticity).
- It uses a secret key along with the hash function, which means only parties with the correct key can generate or verify the HMAC.

## My questions
Based on this [article](https://freedium.cfd/https://medium.com/asecuritysite-when-bob-met-alice/key-based-hashing-2a45e43bb014), I am struggling to understand exactly how or even why HMACs are used for password security. I mean, isn't a strong Bcrypt enough? We are talking about a key derivation function that automatically salts a password, hash a high or moderately high iteration count and makes the computation of the output hash function highly memory/GPU resource intensive. Wouldn't that be sufficient?

And one more thing. The article mixes the terms "encrypting" and "hashing" a little bit. It starts off with:
- "And, so, yesterday, one student asked if an encryption key could be used with a hash." 

Later, when it explains what HMACs are, the article says:
- "HMAC (Hash-based Message Authentication Code) can be used to verify the integrity and authentication of a message. It involves hashing the message with a secret key and thus differs from standard hashing, which is purely a one-way function."

Private and public keys are one-way functions, but NOT hash functions. So why is the process (in the second sentence) referred to as "hashing"? It says that it differs from the ordinary one-way hashing, but isn't the purpose of hashing is to be entirely one-way? And I am also don't understand what exactly is a HMAC. The article starts with bringing two ideas together. Hashing and encryption. If I do a google search on whether or not a HMAC encrypts or not, this is what I get back.

![image](https://github.com/user-attachments/assets/880a04fe-d1d5-4959-859c-7b06a1b8d31e)

### Afterthought
So, it would be highly appreciated if you could explain to me how they work. \:) I will look into the whole PDF as soon as I have the time for it, but right now, this is what caught my attention. I kind of also need of need it for my book. Right now, I close the "Introduction to KDFs (Key Derivation Functions)" section with this, but before this paragraph there needs to be a clarification concerning HMACs:

"Again, cryptography is intricate, and involves a lot of math: for how these got mashed up together is another story. Don’t bother trying to understand the inner workings of these complex functions, such as those of KDF’s and HMAC’s. Alternatively, think of these functions as building blocks. Lego blocks. Lego blocks that you may or may not be able to click, match together. Alone, blocks are just blocks, but when put together, they can create something truly amazing. The HMAC-SHA-256 is a block like that; PBKDF2 is too."

##### Really, really side note:
- My aim in this book is to be practical and to not let my readers get lost in the complexities of these cryptographic algorithms. I get the  general idea of what an HMAC is, but I feel like I need to fully understand it in detail first before I can accurately explain it to my readers. I need to process all this information and filter it correctly.

**Comment by JakeWnuk** [comment]
Hello, thanks for the positive feedback! Appreciate it.

The reason I suggest HMAC-Bcrypt is partially opinionated, but I can walk through my line of thinking. 

1. The HMAC effectively is used to apply a pepper to every created hash. Without the pepper, cracking the hashes becomes exceedingly difficult. This is stored outside the database and should be difficult to compromise without compromising additional assets. In the case of a runtime vulnerability like SQLi, you may have access to the database table but need additional effort to access other resources.
- More information on peppers: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#peppering

2. Bcrypt has a maximum input length of 72 bytes. If a pepper was applied traditionally, a likely password policy even with an extremely long pepper would be unlikely to fill this full input potential. While the diffusion of the Bcrypt algorithm should be sufficient, by using an HMAC we can guarantee that no matter the policy or user behavior we always fill the full input length.

In my opinion, this makes HMAC-Bcrypt a strong and easy to implement hashing approach that combines the strength of Bcrypt with other beneficial cryptographic concepts that developers can continue to use the code patterns of in various implementations.

---

Additionally, this topic is far away from the original intent of a `PTT` issue, so I would highly suggest looking into the hash cracking communities mentioned in the presentation and refrain from asking here. Those communities can be a great place to ask questions and get thoughts and advice on different aspects of hashing and cryptography. I tend to be fairly active in them as well 😄.

**Comment by bojtalepenye** [comment]
Thanks for sharing your insights! Figured I ask you first, because of the PDF.

I appreciate the thought process behind using HMAC-Bcrypt. I now see that it's a smart way to add extra security with a pepper that stays outside the database, adding a layer of protection even in cases like SQL injection. The approach of maximizing the input length with an HMAC makes sense too, ensuring consistent strength regardless of password policies. Great suggestion, and I’ll look into those communities😊

**Comment by JakeWnuk** [comment]
Absolutely, and if you cannot find me there, I am working on a mailbox for questions that will be posted on my website.

Thanks again for being an active community member.
